ALTER TABLE "Pago" ADD COLUMN "comisionHotmart" DOUBLE PRECISION;
ALTER TABLE "Pago" ADD COLUMN "comisionAsesor" DOUBLE PRECISION;
ALTER TABLE "Pago" ADD COLUMN "montoNeto" DOUBLE PRECISION;
ALTER TABLE "Pago" ADD COLUMN "trm" DOUBLE PRECISION;
